// Generated by gencpp from file TCP_command/tcpCommand.msg
// DO NOT EDIT!


#ifndef TCP_COMMAND_MESSAGE_TCPCOMMAND_H
#define TCP_COMMAND_MESSAGE_TCPCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace TCP_command
{
template <class ContainerAllocator>
struct tcpCommand_
{
  typedef tcpCommand_<ContainerAllocator> Type;

  tcpCommand_()
    : header()
    , pedal_percent(0.0)
    , steering_percent(0.0)
    , engineCut(false)  {
    }
  tcpCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pedal_percent(0.0)
    , steering_percent(0.0)
    , engineCut(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _pedal_percent_type;
  _pedal_percent_type pedal_percent;

   typedef float _steering_percent_type;
  _steering_percent_type steering_percent;

   typedef uint8_t _engineCut_type;
  _engineCut_type engineCut;





  typedef boost::shared_ptr< ::TCP_command::tcpCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TCP_command::tcpCommand_<ContainerAllocator> const> ConstPtr;

}; // struct tcpCommand_

typedef ::TCP_command::tcpCommand_<std::allocator<void> > tcpCommand;

typedef boost::shared_ptr< ::TCP_command::tcpCommand > tcpCommandPtr;
typedef boost::shared_ptr< ::TCP_command::tcpCommand const> tcpCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TCP_command::tcpCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TCP_command::tcpCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace TCP_command

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'TCP_command': ['/home/agbot/agbot_deploy/src/TCP_command/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::TCP_command::tcpCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TCP_command::tcpCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TCP_command::tcpCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TCP_command::tcpCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TCP_command::tcpCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TCP_command::tcpCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TCP_command::tcpCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb9f13edb602ecedcba46b66e50aa708";
  }

  static const char* value(const ::TCP_command::tcpCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb9f13edb602ecedULL;
  static const uint64_t static_value2 = 0xcba46b66e50aa708ULL;
};

template<class ContainerAllocator>
struct DataType< ::TCP_command::tcpCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TCP_command/tcpCommand";
  }

  static const char* value(const ::TCP_command::tcpCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TCP_command::tcpCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 pedal_percent\n\
float32 steering_percent\n\
bool engineCut\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::TCP_command::tcpCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TCP_command::tcpCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pedal_percent);
      stream.next(m.steering_percent);
      stream.next(m.engineCut);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tcpCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TCP_command::tcpCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TCP_command::tcpCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pedal_percent: ";
    Printer<float>::stream(s, indent + "  ", v.pedal_percent);
    s << indent << "steering_percent: ";
    Printer<float>::stream(s, indent + "  ", v.steering_percent);
    s << indent << "engineCut: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.engineCut);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TCP_COMMAND_MESSAGE_TCPCOMMAND_H
